language: node_js
node_js:
- 7
branches:
  only: master
env:
  global:
    - EXTENSION_ID=pllgmedcgbbidcoemgooimddcojgfkdl
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
